### ISSUE TITLE
distribute train

### ISSUE THREAD

**Issue by zhangpingrui** [ajzhai/PEANUT#1]
Hello! I'm so sorry to bother you that I want to know how to successfully use the DDP in train_prediction_model.py. 
Where should I init the process group to avoid error? Or do you have the guidance to help us use the DDP in the code?

**Comment by ajzhai** [comment]
Hi! I have never tried it, but mmsegmentation should have built-in support for distributed training. Have you tried simply changing `distributed` to True here?
https://github.com/ajzhai/PEANUT/blob/5fe8358bece89645f7651e524234f967215fa4ac/prediction/train_prediction_model.py#L318

If it doesn't work immediately, maybe you could follow what they do here:
https://github.com/ajzhai/PEANUT/blob/5fe8358bece89645f7651e524234f967215fa4ac/prediction/tools/train.py#L150

**Comment by zhangpingrui** [comment]
> Hi! I have never tried it, but mmsegmentation should have built-in support for distributed training. Have you tried simply changing `distributed` to True here?
> 
> https://github.com/ajzhai/PEANUT/blob/5fe8358bece89645f7651e524234f967215fa4ac/prediction/train_prediction_model.py#L318
> 
> If it doesn't work immediately, maybe you could follow what they do here:
> 
> https://github.com/ajzhai/PEANUT/blob/5fe8358bece89645f7651e524234f967215fa4ac/prediction/tools/train.py#L150

Ah! Thanks for your reply!
I have tried that, but it didn't work.
There are still some other places in code that have to change, and must use the MMDDP, DDP in torch can't work in this situation. (That's why I failed) And now I have solved it already. (This Single2Multi problem really makes me bald hhhhhh)

**Comment by ajzhai** [comment]
Great to hear that you solved it!
