### ISSUE TITLE
Semantic Map Dataset for MP3D

### ISSUE THREAD

**Issue by ytliu74** [ajzhai/PEANUT#10]
Hi, thanks so much for your wonderful work.

Could you please share the semantic map dataset for MP3D? There the HM3D one is shared in the repo. Thanks!

**Comment by ajzhai** [comment]
Yes, here is a drive link: https://drive.google.com/file/d/14kyQZcVmk26ycdf29fIvxTmNvQrrymO4/view

**Comment by ytliu74** [comment]
Thank you so much!

**Comment by zebralan1** [comment]
Thanks for your map. Could you please share the semantic categories of the map? I found the map with 27 channels. (4+22+1) But the number of categories in MP3D is 21.

**Comment by zebralan1** [comment]
> Yes, here is a drive link: https://drive.google.com/file/d/14kyQZcVmk26ycdf29fIvxTmNvQrrymO4/view

Thanks for your map. Could you please share the semantic categories of the map? I found the map with 27 channels. (4+22+1) But the number of categories in MP3D is 21. Thanks!

**Comment by ajzhai** [comment]
For the first 4 channels, they are described in our paper:
Channels 1 and 2 represent the obstacle map and the explored areas. Channels 3 and 4 contain the agent’s current
location and all past locations.

For the 23 vs 22, I think the extra channel may be unnecessary and you can ignore that.

**Comment by zebralan1** [comment]
Thank you so much for your help!
