### ISSUE TITLE
which version of habitat?

### ISSUE THREAD

**Issue by BaiLing09** [ajzhai/PEANUT#2]
According the "File Setup" part, using the episode dataset will happen a wrong which can't distinguish the key "scene_dataset_config" in the [episode dataset].

**Comment by BaiLing09** [comment]
the wrong is 
"File "/home/hp/Project/PEANUT/dependencies/habitat-lab/habitat/datasets/object_nav/object_nav_dataset.py", line 128, in from_json
    episode = ObjectGoalNavEpisode(**episode)
TypeError: __init__() got an unexpected keyword argument 'scene_dataset_config'"

**Comment by ajzhai** [comment]
I recommend running the code with the provided Docker image, which has all the habitat dependencies already installed. Are you able to use that?

**Comment by BaiLing09** [comment]
Hello, Could you tell me how to use the ground-truth segmentation of MP3D and HM3D?
Bacause I meet another problem. When I change the '--use_gt_seg' paremeter to 1 in arguments.py, the 'info['goalseg'] = observations['goalseg']' in peanut_agent.py will throw 'keyError: 'goalseg'' . 

What's more, When I use MP3D and output the semantic sensor result, I find semantic sensor perspective differ from RGB and depth sensors, but this three kinds of sensors are same state. Following is the result:
![屏幕截图 2023-12-26 143215](https://github.com/ajzhai/PEANUT/assets/88820884/44d7c7d2-d2dc-405c-bfb2-334ee822c5de)

And when I use HM3D, I can't get segmentation from semantic sensor, although I have download the 'xxxx.semantic.glb' for scene datasets and add the 'SEMANTIC_SENSOR' in the yaml.

Thanks

**Comment by ajzhai** [comment]
In order to let Habitat load the semantic annotations, you need to set the `SIMULATOR.SCENE_DATASET` variable in the config. This can be done in your code, for example try adding this line
```config.SIMULATOR.SCENE_DATASET = 'habitat-challenge-data/data/scene_datasets/hm3d/hm3d_annotated_basis.scene_dataset_config.json'```
around here
https://github.com/ajzhai/PEANUT/blob/5fe8358bece89645f7651e524234f967215fa4ac/nav/collect.py#L26

You can also do this in the config yaml. Let me know if it works!

**Comment by BaiLing09** [comment]
Thanks for your help. 

But only setting ``config.SIMULATOR.SCENE_DATASET`` can't fit this problem in habitat-challenge enviroment (tags/challenge-2022), I have to delete ``self._config.SIMULATOR.SCENE_DATASET = (
    self.current_episode.scene_dataset_config
)`` in ``habitat-lab/habitat/core/env.py`` of habitat-lab library so that I can solve this problem.

**Comment by dwiwekan** [comment]
Hii, I observe this discussion thoroughly. I follow all steps that you have mentioned here and yet the semantic sensor does not even detect object like bed, toilet and so on. Can you provide more instruction about this? Thank you!

**Comment by BaiLing09** [comment]
> Hii, I observe this discussion thoroughly. I follow all steps that you have mentioned here and yet the semantic sensor does not even detect object like bed, toilet and so on. Can you provide more instruction about this? Thank you!

Could you show your semantic sensor output, so that I can check the problem. First, you need to check the habitat version, you need to use "tags/challenge-2022" version for this project. Besides, if your semantic sensor has output, you need to use the following code to display: 

from PIL import Image
import numpy as np


def display_sample(semantic_obs, depth_obs=None):
    from habitat_sim.utils.common import d3_40_colors_rgb

    semantic_img = Image.new("P", (semantic_obs.shape[1], semantic_obs.shape[0]))
    semantic_img.putpalette(d3_40_colors_rgb.flatten())
    semantic_img.putdata((semantic_obs.flatten() % 40).astype(np.uint8))
    semantic_img = semantic_img.convert("RGBA")

    if depth_obs is not None:
        depth_img = Image.fromarray((depth_obs[:, :, 0] * 255).astype(np.uint8), mode="L")
        return np.array(semantic_img), np.array(depth_img)

    return np.array(semantic_img)   # use opencv to display

What's more, if you want to use gt class label, you need to map the semantic sensor output (the output indicates the object id in this scene) to corresponding class label according to the xxxxxxx.semantic.txt (in each scene folder)  and 'category_mapping.tsv' (https://github.com/facebookresearch/habitat-sim/blob/challenge-2022/data/matterport_semantics/matterport_category_mappings.tsv)

**Comment by dwiwekan** [comment]
Thank you for replying to me. It works for segmentation! Here is my semantic segmentation result using your code (I didn't convert to RGBA).
![Image](https://github.com/user-attachments/assets/2c4019af-5e37-4d99-b6c4-9c49c355f209)

Also, I implemented some code from here to use Segmentation: 
https://github.com/ybgdgh/Frontier-Semantic-Exploration
At this point, I don't know why the segmentation didn't detect the properly
![Image](https://github.com/user-attachments/assets/aab00125-c71a-4285-bccf-a2a252627596)
